### ISSUE TITLE
Record Audit Logs

### ISSUE THREAD

**Issue by yusuke-sforzando** [sforzando/q-lako#11]
## Is your feature request related to a problem? Please describe

Record the user's activity history in a log file.

## Describe the solution you'd like

Record the user's activity history in the GCS.

Example:)

```
YYYY-MM-DDTHH:MM:SS.fff User A logged in.
```

## Additional context

(T.B.D)

**Comment by shin-sforzando** [comment]
`YYYY_MM/DD HH:SS.` こんな時間表記フォーマット見たことないぞ…

**Comment by yusuke-sforzando** [comment]
すいません。
この書き方はどうでしょうか。
`yyyy-MM-dd HH:mm:ss`

ログファイルに関しては、
`%YYYYMMDD%%HHMMSS%.log`
こちらの方が良い気もしますが、命名に関しては、このイシューで考えていこうと思います。

いずれにせよ、この書き方は常識外れだと思うので修正します。ありがとうございます。

**Comment by shin-sforzando** [comment]
時間フォーマットは特段の理由がない限りISO8601でしょ。
https://ja.wikipedia.org/wiki/ISO_8601

**Comment by yusuke-sforzando** [comment]
なるほど！では、YYYY-MM-DDThh:mm:ss+09:00の拡張形式で統一しようと思います。
ありがとうございます！
CSV等で保存する場合は、可読性の高い拡張形式: `YYYY-MM-DDThh:mm:ss+09:00`
ファイルシステム等で保存する場合は、念のため基本形式: `YYYYMMDDThhmmss+0900`
で統一する方向で進めます。

**Comment by shin-sforzando** [comment]
いや、Pythonなら何も考えずに脳死で `datetime.isoformat` 使っておけば良い。
https://docs.python.org/3/library/datetime.html#datetime.datetime.isoformat

厳密にはタイムゾーンが絡む場合と禁則文字が絡む場合だけ脳死じゃダメだけど、
少なくともCSV or FSとかでフォーマット切り替える必要はないです。

**Comment by yusuke-sforzando** [comment]
なるほどですね。承知しました。
一点今疑問が湧いたので、細かいことですが質問させてください。

qlakoの場合`YYYY-MM-DDTHH:MM:SS.ffffff`においてマイクロ秒単位で記録する必要はないと考えていますが、
一般的にログというものはマイクロ秒まで記録しておくようなものですか？
sfzでは何かルール等ありますでしょうか、後学までに教えていただきたいです。

**Comment by shin-sforzando** [comment]
結論から言えば「取れるならマイクロ秒まで」。
単純に組み込み系だとms単位、音響映像系でも1/60s単位で動いているわけだし、
Webアプリケーションの場合でも1秒間に1回以上のアクセスがあるなら、 `HH:MM:SS` では足りない。
ただし、そもそもPCの時計はそれほど精密じゃないし、複数台となれば時計があってない可能性もあり、
ネットワークを介した場合は遅延も考慮しなければならないため、マイクロ秒単位で記録されてても参考程度にしか信用できない。
だから、「取れるならマイクロ秒まで取っておけば？（絶対に取れとは言わない）」が現実解。

**Comment by yusuke-sforzando** [comment]
なるほど！理解しました！
ご丁寧にありがとうございます！

**Comment by shin-sforzando** [comment]
2020/10/08中に完了予定。

**Comment by shin-sforzando** [comment]
ちょっと議論したいんだけど、
> Record the user's activity history in the GCS.

って本当かな？
例えば、今回CloudSQL使う割りに読み込みにしか使わないのもったいないから、CloudSQLにAuditLogs書き込んだりするのはどうだろう？

**Comment by yusuke-sforzando** [comment]
なるほどですね、データベースにログを入れる、というのがちょっとイメージできていないです。
私のログのイメージは、1日ごとにファイル化されているようなものでした。
でも、この場合、ユーザーの振る舞いにしかすぎないので、データベースに入ってあってもいいような気もします。

**Comment by shin-sforzando** [comment]
じゃ、それで。
