### ISSUE TITLE
List the search results with Amazon PA-API

### ISSUE THREAD

**Issue by yusuke-sforzando** [sforzando/q-lako#11]
## Is your feature request related to a problem? Please describe.

List the search results with Amazon PA-API.

## Describe the solution you'd like

1. main.py
    - Receive string from `GET /search_result`
    - Run `amazon_api_client.search_products(keywords=***)`
    - Format response data from Amazon PA-API to show as list
        - e.g. `products_list = [{"asin": aaaa, "title": bbbb, "image_url": cccc} , … , {"asin": xxxx, "title": yyyy, "image_url": zzzz}]
    - Run `render_template("search_result.html",  **context_dict)` with formatted data
1. search_result.html
    - Show data with Jinja template
        - Each asset is displayed with `<div>`  as shown below
    - Push「選択する」button then request to `GET /registration-details` with asin code
1. registration-details.html, main.py
    - The string to be GETed is displayed as is

```html
{% for product in products_list %}
<div>
  <image src="{{ product.image_url }}" />
  <h2>{{ product.title }}</h2>
  <form action="/registration-details" method="get">
    <div>
      <input type="hidden" name="asin" value="{{ product.asin }}" >
      <button>選択する</button>
    </div>
  </form>
</div>
{%- endfor %}
```

## Additional context

Next issue is #13

**Comment by tomoya-sforzando** [comment]
1.0で実装済みなのでclose
