### ISSUE TITLE
Record Application Logs

### ISSUE THREAD

**Issue by yusuke-sforzando** [sforzando/q-lako#12]
## Is your feature request related to a problem? Please describe.

Record system behavior in Stackdriver.

## Describe the solution you'd like

- Setup Google Cloud Logging
- Setup logging.Logger of Python

- cf. [Python 用 Cloud Logging の設定  |  Google Cloud](https://cloud.google.com/logging/docs/setup/python?hl=ja#connecting_the_library_to_python_logging)

## Additional context

(T.B.D.)

_Updated at 2020-10-09 01:08:00 by Kashimada_

**Comment by shin-sforzando** [comment]
2020/10/08中に完了予定。
