### ISSUE TITLE
Show details of the search results with Amazon PA-API

### ISSUE THREAD

**Issue by yusuke-sforzando** [sforzando/q-lako#13]
## Is your feature request related to a problem? Please describe.

Show details of the search results with Amazon PA-API.

## Describe the solution you'd like

1. main.py
    - Receive `asin` from `GET /search_result`
    - Run`amazon_api_client.search_products(keywords=***)`
    - Format response data from Amazon PA-API to show as details
        - → dataclass `Asset`
    - Run `return render_template("registration-details.html",  **context_dict)`
1. registration-details.html
    - Show data with Jinja template as shown below

```html
<div>
  <h1>登録内容詳細</h1>
  <image src="VALUE_FROM_AMAZON_PA-API" />
  <p>商品名/書籍名: TITLE_FROM_AMAZON_PA-API</p>
  …
  <p>登録者: VALUE_OF_REGISTRANT_NAME</p>
</div>
```

## Additional context

`registered_at` not need to display because it is automatically filled at posted.

Next issue #14 and #16

**Comment by tomoya-sforzando** [comment]
1.0で実装済みなのでclose
