### ISSUE TITLE
Create a drop-down list of registration locations and registrants

### ISSUE THREAD

**Issue by yusuke-sforzando** [sforzando/q-lako#15]
## Is your feature request related to a problem? Please describe.

I would like to be able to select some registration information in the dropdown.

## Describe the solution you'd like

- settings.ini
    - set `positions=…`
    - set `registrants=…`
- main.py
    - set `positions` and `registrants` to context_dict
- registration-details.html
    - set dropdown for positions and registrants

```html
<form>
  <label for="position_id">保管場所: </label>
  <select name="default_position" id="position_id">
    {% for position in positions %}
    <option value="{{ position }}">{{ position }}</option>
    {%- endfor %}
  </select>
</form>
```

## Additional context

Related to #14 and #16 .

**Comment by tomoya-sforzando** [comment]
1.0で実装済みなのでclose
