### ISSUE TITLE
Implement a registration button

### ISSUE THREAD

**Issue by yusuke-sforzando** [sforzando/q-lako#16]
## Is your feature request related to a problem? Please describe.

Implement submit and cancel buttons in registration-details.html.  
Run registration to Airtable.

## Describe the solution you'd like

1. registration-details.html
    - Implement a cancel button to back browser history
    - Implement a submit button to send details to `POST /registration-details` 
1. main.py
    - Receive data from `POST /registration-details`
    - Convert received data to dataclass `Asset`
    - Run `register_asset()`
    - Then go to Index

```html
<div>
  <form action="/registration-details" method="post">
    …
    <div>
        <input type="button" value="キャンセル" onClick="history.back()" />
        <input type="submit" value="登録" />
    </div>
  </form>
</div>
```

## Additional context

#14 assumes that it has been implemented.

**Comment by tomoya-sforzando** [comment]
1.0で実装済みなのでclose
