### ISSUE TITLE
Set up CI Environment

### ISSUE THREAD

**Issue by yusuke-sforzando** [sforzando/q-lako#2]
## Is your feature request related to a problem? Please describe.

Build a CI environment that automatically executes Update, Lint, and Test.

## Describe the solution you'd like

Run python-ci.yml in GitHub Actions.
Use `pip`,`flake8` and `pytest` to perform each operation.

## Additional context

#3 has been split.

[GitHub ActionsでのPythonの利用](https://docs.github.com/ja/actions/language-and-framework-guides/using-python-with-github-actions)

**Comment by yusuke-sforzando** [comment]
# .gitignore

Use gitignore.io to create a `.gitignore` file.

![Screen Shot 2020-10-01 at 10 34 12](https://user-images.githubusercontent.com/67737076/94756162-a9fe5e00-03d1-11eb-905a-d6f7ee933aab.png)

**Comment by shin-sforzando** [comment]
2020/10/07中に完了予定。
