### ISSUE TITLE
Implement Vue.js

### ISSUE THREAD

**Issue by yusuke-sforzando** [sforzando/q-lako#23]
## Is your feature request related to a problem? Please describe.

We used `Vue.js` to organize the front-end screens.

## Describe the solution you'd like

In the future, it will be linked to Flask.

- `Node.js`
- `npm`
- `Vue CLI`

## Additional context

In the future, it will be linked to Flask.

**Comment by shin-sforzando** [comment]
Vue.jsを導入しないことになったため、 `wontfix` でClose。
