### ISSUE TITLE
Implement Flask

### ISSUE THREAD

**Issue by yusuke-sforzando** [sforzando/q-lako#24]
## Is your feature request related to a problem? Please describe.

As it stands now, there is no way to output the HTML data to the browser.
Create a simple, HTML page using Flask.

## Describe the solution you'd like

Use Flask to handle the inner workings of `q-lako`.

Add `Flask` to `requirements.txt` .

```shell
pip install -r requirements.txt
python src/main.py
```

## Additional context

None.

**Comment by shin-sforzando** [comment]
2020/10/07中に完了予定。
