### ISSUE TITLE
Implement Tailwind CSS

### ISSUE THREAD

**Issue by yusuke-sforzando** [sforzando/q-lako#25]
## Is your feature request related to a problem? Please describe.

Define the style of the details of the UI created in `Flask`.
The current HTML output from Flask does not strictly define color, size and position.
This ambiguity is solved by using Tailwind CSS.

The goal here is to move the displayed `hello world` to the **Center** of the screen.

## Describe the solution you'd like

Set the element's style using Tailwind CSS.
Embed CSS structure in the template output from Flask.

## Additional context

It is used in combination with Flask.
I am considering implementing it on the CDN...
[ローカル環境でシンプルにtailwindcssのみを構築する](https://qiita.com/torano_tomo/items/c04c144dc909559f7d6e)
[初めてでもわかるTailwindcss入門](https://reffect.co.jp/html/tailwindcss-for-beginners)

**Comment by shin-sforzando** [comment]
2020/10/07中に完了予定。
