### ISSUE TITLE
Set up code coverage measurement for unit test

### ISSUE THREAD

**Issue by yusuke-sforzando** [sforzando/q-lako#3]
## Is your feature request related to a problem? Please describe.

Build a code coverage measurement environment for unit tests.

## Describe the solution you'd like

We build a unit test environment.
The targets of the unit tests are Python File.

## Additional context

[Flaskアプリケーションのテスト](https://msiz07-flask-docs-ja.readthedocs.io/ja/latest/testing.html#the-first-test)

**Comment by shin-sforzando** [comment]
2020/10/07中に完了予定。

**Comment by shin-sforzando** [comment]
#29 と #30 に分割したのでClose。
