### ISSUE TITLE
Determine if there are any duplicates in Airtable

### ISSUE THREAD

**Issue by yusuke-sforzando** [sforzando/q-lako#6]
## Is your feature request related to a problem? Please describe.

I want to check for duplicate supplies and books.

## Describe the solution you'd like

Make a function to determine whether the input ASIN/ISBN code is registered in Airtable or not.
Create a function that returns False if the code is registered and True if it is not registered.

## Additional context

None.

**Comment by tomoya-sforzando** [comment]
#35 で同時に対応予定ということでこちらのIssueは閉じます
