### ISSUE TITLE
Register your supplies or books in Airtable

### ISSUE THREAD

**Issue by yusuke-sforzando** [sforzando/q-lako#7]
## Is your feature request related to a problem? Please describe.

I want to register my Amazon items with Airtable.

## Describe the solution you'd like

Implement the ability to register a dictionary with the appropriate key and value to Airtable.

## Additional context

None.

**Comment by shin-sforzando** [comment]
> Create a function to register Airtable with a dictionary with appropriate key names as arguments.

直訳すると「適切なキー名を引数として辞書にAirtableを登録する関数を作成します。」
Airtableを登録するんじゃない、Airtableに登録。
Implement the ability to register a dictionary with the appropriate key and value to Airtable. とかじゃないですかね。

**Comment by yusuke-sforzando** [comment]
そうですね。
修正いたします。
